version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            -   ./config:/app/config
            -   ./screenshots:/app/screenshots
        command: python3 main.py